//Testing logging data
d3.json("../assets/data/genres.json").then((data) => {
  console.log(data);
});

const margin = {top: 10, right: 20, bottom: 30, left: 50},
    width = 1500 - margin.left - margin.right,
    height = 900 - margin.top - margin.bottom;

//Create svg element
const canvas = d3.select("body");
const svg = canvas.append("svg")
  .attr("width", width + margin.left + margin.right)
  .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform",
    "translate(" + margin.left + "," + margin.top + ")");

//Reading data
d3.json("../assets/data/genres.json").then((data) => {

  //Add x axis
  const x = d3.scaleLinear()
    .domain([0, 1])
    .range([0, width]);
  svg.append("g")
    .attr("transform", "translate(0," + (height - 50) + ")")
    .call(d3.axisBottom(x));
  //Add y axis
  const y = d3.scaleLinear()
    .domain([0,1])
    .range([height - 50, 0]);
  svg.append("g")
    .call(d3.axisLeft(y));
  //Add x axis label
  svg.append("text")
    .attr("text-anchor", "end")
    .attr("x", width)
    .attr("y", height)
    .attr("font-size", "px")
    .text("Energy")
  
  //Add a scale for bubble size
  const z = d3.scaleLinear()
    .domain([0, 5])
    .range([0, 10]);

  //Add a scale for bubble color
  const myColor = d3.scaleOrdinal()
    .domain(['celticmetal',
    'balkantrap',
    'deepchill-out',
    'slovakrock',
    'ghanaianhiphop',
    'e6fi',
    'ostrock',
    'slovakindie',
    'persiantraditional',
    'albanianhiphop',
    'modernblues',
    'canadianpop',
    'portuguesefolk',
    'belgianpop',
    'runefolk',
    'psychill',
    'deepcomedy',
    'lapop',
    'balletclass',
    'khmer',
    'groovemetal',
    'pianoblues',
    'dronemetal',
    'dreampop',
    'swedishindiepop',
    'undergroundpowerpop',
    'sungpoetry',
    'mexicanrock-and-roll',
    'minimaldub',
    'belgianmetal',
    'raregroove',
    'newrave',
    'japanesedeathmetal',
    'arabichiphop',
    'italianbaroque',
    'gothicmetal',
    'worship',
    'undergroundlatinhiphop',
    'norwegianmetal',
    'dronefolk',
    'zeuhl',
    'oratory',
    'mathpop',
    'romanianfolk',
    'sinhala',
    'deeplatinjazz',
    'alternativeamericana',
    'birminghamindie',
    'bostonmetal',
    'go-go',
    'tropicalhouse',
    'spanishfolk',
    'russianpunk',
    'canadianrock',
    'country',
    'liverpoolindie',
    'gabba',
    'substep',
    'mandepop',
    'doo-wop',
    'darktechno',
    'salsa',
    'deepbrazilianpop',
    'thaipop',
    'torontoindie',
    'messianicpraise',
    'blues-rock',
    'psychedelicfolk',
    'deeppsychobilly',
    'reggaerock',
    'elpasoindie',
    'germanhardcore',
    'belfastindie',
    'hongkongindie',
    'germanoi',
    'organicambient',
    'scratch',
    'reading',
    'beats',
    'ecuadorianindie',
    'v-pop',
    'keroncong',
    'funkrock',
    'futurefunk',
    'fluxwork',
    'alaskaindie',
    'deepdeephouse',
    'essexindie',
    'volksmusik',
    'nuelectro',
    'psychedelictrance',
    'jazzfusion',
    'zapstep',
    'vaporpop',
    'deepfilthstep',
    'minimaltechno',
    'danishpoprock',
    'muzicacrestina',
    'metalguitar',
    'hardglam',
    'africangospel',
    'dmvrap',
    'vintageradioshow',
    'italianundergroundhiphop',
    'arpaparaguaya',
    'finnishhiphop',
    'swedishsoul',
    'indonesianpoppunk',
    'channelpop',
    'bmore',
    'hiphop',
    'ukpop',
    'electrolatino',
    'portugueseindie',
    'breakcore',
    'minneapolisindie',
    'nlfolk',
    'christianpop',
    'classicalpercussion',
    'noisepunk',
    'experimentalhouse',
    'norwegianhiphop',
    'glittertrance',
    'deeppoppunk',
    'reggaeton',
    'cumbiaperuana',
    'frenchhiphop',
    'musiqueacadienne',
    'deeprai',
    'americanchoir',
    'ukamericana',
    'chamame',
    'reggae',
    'deepccm',
    'r&bbrasileiro',
    'punta',
    'italianpost-rock',
    'hardcorepunk',
    'microhouse',
    'neo-tradmetal',
    'melodicdeathmetal',
    'deathgrind',
    'melodicmetalcore',
    'animescore',
    'detroitindie',
    'colombianrock',
    'showtunes',
    'ghettotech',
    'musicbox',
    'dubstep',
    'turkishexperimental',
    'steelguitar',
    'vintagehawaiian',
    'experimentalpsych',
    'frenchfolk',
    'persianneo-traditional',
    'neuedeutschewelle',
    'icelandicpop',
    'gauzepop',
    'shanty',
    'christmas',
    'chiphop',
    'musikanak-anak',
    'swedishsynthpop',
    'minimaldubstep',
    'scorecore',
    'peruvianindie',
    'geekrock',
    'buffalonyindie',
    'ambeat',
    'mallet',
    'belgianindierock',
    'otacore',
    'drumandbass',
    'chillstep',
    'atmosphere',
    'rootsreggae',
    'deepragga',
    'midwestemo',
    'visualkei',
    'salsainternational',
    'chicagopunk',
    'anthemworship',
    'electronicore',
    'canteflamenco',
    'sludgemetal',
    'welshchoir',
    'southernamericana',
    'musicadepernambuco',
    'pixie',
    'turkishfolk',
    'norwegianchoir',
    'technicalblackmetal',
    'balticfolk',
    'ecuadoria',
    'monterreyindie',
    'dominicanindie',
    'indietico',
    'collegemarchingband',
    'hollywood',
    'classicaltrumpet',
    'medieval',
    'albuquerqueindie',
    'kwaito',
    'canadianelectropop',
    'grungepop',
    'israeliindie',
    'finnishedm',
    'experimentalhiphop',
    'russianjazz',
    'basquerock',
    'edm',
    'skyroom',
    'austrianhiphop',
    'tassieindie',
    'modernperformance',
    'traditionalbritishfolk',
    'demoscene',
    'deepdubtechno',
    'focus',
    'epicore',
    'cumbiapop',
    'deepeurodance',
    'bubbletrance',
    'northeastenglandindie',
    'popedm',
    'vocaljazz',
    'greekhouse',
    'progressivebreaks',
    'ukpost-punk',
    'drumfunk',
    'neurostep',
    'portugueseearlymusic',
    'earlyavantgarde',
    'classicsoundtrack',
    'columbusohioindie',
    'irishfolk',
    'sanantonioindie',
    'mexicanedm',
    'rockkapak',
    'deepsoundtrack',
    'bretonfolk',
    'tahitian',
    'renaissance',
    'swedishrockabilly',
    'dronescape',
    'austrianmetal',
    'deeppower-poppunk',
    'trapfrancais',
    'countrydawn',
    'moderncountryrock',
    'progressivebluegrass',
    'albertacountry',
    'venezuelanhiphop',
    'metallichardcore',
    'latinmetal',
    'turkishelectronic',
    'glitchbeats',
    'norwegiandeathmetal',
    'finnishblackmetal',
    'polishblackmetal',
    'videogamemusic',
    'darkpost-punk',
    'cyberpunk',
    'colombianindie',
    'wrock',
    'steampunk',
    'traditionalenglishfolk',
    'vintagechanson',
    'brazilianelectronica',
    'icelandicrock',
    'britishbrassband',
    'swissindie',
    'petcalming',
    'panpipe',
    'j-core',
    'brightonindie',
    'musiikkialapsille',
    'icelandicindie',
    'bouncyhouse',
    'lowercase',
    'tijuanaelectronic',
    'intelligentdancemusic',
    'dancerock',
    'danishindiepop',
    'rapmetalcore',
    'okindie',
    'trance',
    'progressivetrance',
    'orchestralperformance',
    'chicagohouse',
    'jerseyclub',
    'dubsteppe',
    'argentineindie',
    'darkcabaret',
    'classify',
    'swing',
    'estonianhiphop',
    'chaoticblackmetal',
    'turkishmetal',
    'necrogrind',
    'indonesianworship',
    'acappella',
    'polishclassical',
    'ukdiypunk',
    'swisscountry',
    'gothicsymphonicmetal',
    'popemo',
    'welshmetal',
    'vikingmetal',
    'mexicanpoppunk',
    'alternativeemo',
    'crossoverthrash',
    'futureambient',
    'chineseexperimental',
    'greekblackmetal',
    'coventryindie',
    'portuguesepop',
    'leedsindie',
    'trikiti',
    'czechindie',
    'vaporsoul',
    'guitarcase',
    'goatrance',
    'christianrelaxative',
    'norwegianfolk',
    'outerhiphop',
    'neosoul-jazz',
    'malmoindie',
    'britishcomedy',
    'etherpop',
    'koreanmetal',
    'chicagoindie',
    'ecuadorianalternativerock',
    'flemishfolk',
    'esperanto',
    'indienapoletano',
    'peruvianmetal',
    'chanson',
    'classicalsaxophone',
    'irishclassical',
    'bahai',
    'italianoccultpsychedelia',
    'deepsoftrock',
    'indonesianpop',
    'newromantic',
    'freestyle',
    'emorap',
    'canterburyscene',
    'norwegianindie',
    'corsicanfolk',
    'swedishprog',
    'vintagegospel',
    'germanworship',
    'darkambient',
    'hardvapour',
    'deepidm',
    'darkwave',
    'madchester',
    'bedroompop',
    'norwegianpunk',
    'funeraldoom',
    'hiphouse',
    'germanpop',
    'finnishjazz',
    'britishjazz',
    'chineseguzheng',
    'deepgroovehouse',
    'indiegaragerock',
    'indonesianhiphop',
    'vegasindie',
    'frenchpunk',
    'deepindierock',
    'christianacappella',
    'classicalbaritone',
    'italianrenaissance',
    'darkprogressivehouse',
    'slavicmetal',
    'uknoiserock',
    'darktrap',
    'musicaperbambini',
    'earlymusic',
    'atmosphericpost-metal',
    'rvaindie',
    'danishpop',
    'portugueserock',
    'indianindie',
    'milanindie',
    'afropsych',
    'celtic',
    'estonianjazz',
    'tango',
    'nuevacancion',
    'rapdominicano',
    'riddim',
    'swedishdeathmetal',
    'instrumentalprogressivemetal',
    'classicalguitarquartet',
    'vietnamesebolero',
    'deepnorteno',
    'post-metal',
    'mathcore',
    'chineseopera',
    'chiptune',
    'abstractidm',
    'marchafunebre',
    'darkblackmetal',
    'hardminimaltechno',
    'nativeamericanhiphop',
    'polynesianpop',
    'noisepop',
    'gothicrock',
    'arabalternative',
    'hungarianpunk',
    'ukalternativepop',
    'polishfolk',
    'rosary',
    'hardstyle',
    'catalanfolk',
    'sunsetlounge',
    'dallasindie',
    'psychedelicblues-rock',
    'dancepop',
    'scottishhiphop',
    'italianindiepop',
    'rocktico',
    'latinchristian',
    'galicianfolk',
    'christianafrobeat',
    'michiganindie',
    'vocaltrance',
    'smoothjazz',
    'azeripop',
    'panamanianrock',
    'canadiansoundtrack',
    'classicdanishpop',
    'euroska',
    'cornwallindie',
    'czechrock',
    'soul',
    'germanpunk',
    'canadianclassical',
    'classicalsaxophonequartet',
    'germanpost-rock',
    'skweee',
    'belgianexperimental',
    'quietstorm',
    'garagerock',
    'seattleindie',
    'phoenixindie',
    'polyphony',
    'psychedelicrock',
    'classicswedishpop',
    'germanjazz',
    'greenlandicpop',
    'scandinavianr&b',
    'alternativer&b',
    'crustpunk',
    'frenchfolkpop',
    'cornetasytambores',
    'germanrenaissance',
    'rocknacional',
    'gospelblues',
    'nordiccontemporaryclassical',
    'newjackswing',
    'gospelr&b',
    'idahoindie',
    'rock',
    'dunedinindie',
    'dublinindie',
    'deepfunk',
    'rebetiko',
    'post-rocklatinoamericano',
    'cubaton',
    'porro',
    'post-blackmetal',
    'peruvianhiphop',
    'rumbacatalana',
    'germanhardrock',
    'vallenato',
    'swedishpoppunk',
    'aussieemo',
    'drillandbass',
    'moog',
    'czechelectronic',
    'electronica',
    'russianelectronic',
    'psalmen',
    'symphonicpowermetal',
    'schoolensemble',
    'norwegianclassical',
    'cancoesinfantis',
    'latinfunk',
    'urbancontemporary',
    'classicsoul',
    'halifaxindie',
    'hi-nrg',
    'westernmassindie',
    'historicallyinformedperformance',
    'protopunk',
    'victoriabcindie',
    'brazilianska',
    'j-dance',
    'frenchopera',
    'popping',
    'depressiveblackmetal',
    'oberkrainer',
    'indieemorock',
    'newwavepop',
    'europop',
    'yugoslavrock',
    'romanianindie',
    'neoclassical',
    'guatemalanindie',
    'indiepoptimism',
    'czechfolk',
    'jazzelectricbass',
    'danishclassical',
    'deepsmoothjazz',
    'post-disco',
    'r&b',
    'martialindustrial',
    'melbourneindie',
    'deepdisco',
    'lgbtq+hiphop',
    'dansktop',
    'brazilianindierock',
    'spiritualjazz',
    'americanfolkrevival',
    'acousticpunk',
    'progressiveupliftingtrance',
    'microtonal',
    'electronic',
    'witchhouse',
    'doujin',
    'germantechno',
    'contemporaryjazz',
    'lateromanticera',
    'minneapolispunk',
    'turkishhiphop',
    'girlgroup',
    'okinawanfolk',
    'atmosphericpost-rock',
    'australianrock',
    'novampb',
    'sydneyindie',
    'stlindie',
    'chamberensemble',
    'traditionalfolk',
    'hippop',
    'funkybreaks',
    'countryrap',
    'poprap',
    'australianundergroundhiphop',
    'folclorcolombiano',
    'italianhiphop',
    'aucklandindie',
    'polishpop',
    'welshindie',
    'christianpunk',
    'classicgaragerock',
    'ambientworship',
    'australianindiefolk',
    'medievalrock',
    'post-romanticera',
    'etherealwave',
    'portlandhiphop',
    'bboy',
    'mellowgold',
    'gbvfi',
    'koreanpop',
    'alternativerootsrock',
    'polishpunk',
    'russianreggae',
    'deepchristianrock',
    'bluesband',
    'chansonpaillarde',
    'nordichouse',
    'rockcatala',
    'rhythmandblues',
    'handsup',
    'chamberchoir',
    'thrashmetal',
    'britishchoir',
    'swedishhardrock',
    'regionalmexicanpop',
    'progressivedeathcore',
    'manitobacountry',
    'historicclassicalperformance',
    'spaceambient',
    'downtempo',
    'romaniantrap',
    'deepsouthernsoul',
    'rapmetal',
    'czechhiphop',
    'classicopm',
    'j-rap',
    'pasodobles',
    'eurovision',
    'southernrock',
    'italianska',
    'mpb',
    'choro',
    'cantautor',
    'undergroundrap',
    'thrashcore',
    'japaneser&b',
    'bossanovajazz',
    'czechpop',
    'freakbeat',
    'kindierock',
    'deepdancepop',
    'finnishworship',
    'fingerstyle',
    'bossanova',
    'earlyromanticera',
    'brazilianreggae',
    'southafricanjazz',
    'hungarianhiphop',
    'latinafrobeat',
    'meditation',
    'australianpop',
    'ranchera',
    'finnishfolk',
    'britishindierock'])
    .range(d3.schemePastel1);
  
  //A tooltip div that is hidden by default
  const tooltip = d3.select("body")
    .append("div")
      .style("opacity", 0)
      .attr("class", "tooltip")
      .style("position", "absolute")
      .style("background-color", "black")
      .style("border-radius", "5px")
      .style("padding", "10px")
      .style("color", "white")

  //3 functions that show/update tooltip based off user mouse movement
  const showTooltip = (d) => {
    // debugger
    tooltip
      .transition()
      .duration(200);
    tooltip
      .style("opacity", 1)
      .html("Genre: " + d.Genre)
      .style("left", (d3.event.pageX+10) + "px")
      .style("top", (d3.event.pageY-10) + "px");
  }
  
  const moveTooltip = (d) => {
    // debugger
    tooltip
      .style("left", (d3.event.pageX+10) + "px")
      .style("top", (d3.event.pageY-10) + "px");
  }

  const hideTooltip = (d) => {
    // debugger
    tooltip
    .transition()
    .duration(200)
    .style("opacity", 0);
  }

  //Add bubbles
  svg.append('g')
    .selectAll("dot")
    .data(data)
    .enter()
    .append("circle")
      .attr("class", "bubbles")
      .attr("cx", (d) => {return x(d.Energy);})
      .attr("cy", (d) => {return y(d.Valence);})
      .attr("r", (d) => {return z(d.time_signature);})
      .style("fill", (d) => {return myColor(d.Genre);})
    //tooltip triggers
    .on("mouseover", showTooltip)
    .on("mousemove", moveTooltip)
    .on("mouseleave", hideTooltip);
});